export const STORE_FETCHED_PLAYLISTS = 'STORE_FETCHED_PLAYLISTS'
export const STORE_POSTED_PLAYLISTS = 'STORE_POSTED_PLAYLISTS'
export const STORE_POST_PLAYLIST = 'STORE_POST_PLAYLIST'
export const STORE_UPDATED_PLAYLISTS = 'STORE_UPDATED_PLAYLISTS'
export const STORE_SEARCH_PLAYLIST = 'STORE_SEARCH_PLAYLIST'
export const STORE_UPDATE_PLAYLIST = 'STORE_UPDATE_PLAYLIST'
export const STORE_DELETED_PLAYLIST = 'STORE_DELETED_PLAYLIST'
export const STORE_DELETE_PLAYLIST = 'STORE_DELETE_PLAYLIST'



